name: 'Analyze Version Bump Type'
description: 'Analyzes commits since last tag to determine version bump type'
inputs:
  last-tag:
    description: 'Last version tag to analyze from'
    required: true
  max-commits:
    description: 'Maximum commits to analyze if no tag found'
    required: false
    default: '10'
outputs:
  bump-type:
    description: 'Determined bump type (major, minor, patch)'
    value: ${{ steps.analyze.outputs.bump-type }}
  changelog:
    description: 'Formatted changelog of commits'
    value: ${{ steps.analyze.outputs.changelog }}
  commit-count:
    description: 'Number of commits analyzed'
    value: ${{ steps.analyze.outputs.commit-count }}

runs:
  using: 'composite'
  steps:
    - name: Analyze commits for bump type
      id: analyze
      shell: bash
      run: |
        LAST_TAG="${{ inputs.last-tag }}"
        MAX_COMMITS="${{ inputs.max-commits }}"

        echo "ðŸ” Analyzing commits since: $LAST_TAG"

        # Get commits since last tag
        if [[ "$LAST_TAG" == "v0.0.0" ]] || [[ -z "$LAST_TAG" ]]; then
          echo "ðŸ“ No previous tag found, analyzing last $MAX_COMMITS commits"
          COMMITS=$(git log --oneline --format="%H %s" HEAD~${MAX_COMMITS}..HEAD 2>/dev/null || git log --oneline --format="%H %s" --max-count=$MAX_COMMITS)
        else
          echo "ðŸ“ Analyzing commits since $LAST_TAG"
          COMMITS=$(git log --oneline --format="%H %s" ${LAST_TAG}..HEAD 2>/dev/null || echo "")
        fi

        if [[ -z "$COMMITS" ]]; then
          echo "âš ï¸ No commits found to analyze"
          echo "bump-type=patch" >> $GITHUB_OUTPUT
          echo "changelog=No recent commits found" >> $GITHUB_OUTPUT
          echo "commit-count=0" >> $GITHUB_OUTPUT
          exit 0
        fi

        # Count commits
        COMMIT_COUNT=$(echo "$COMMITS" | wc -l | tr -d ' ')
        echo "ðŸ“Š Found $COMMIT_COUNT commits to analyze"

        # Analyze commit messages for version bump indicators
        BUMP_TYPE="patch"  # Default to patch

        echo "ðŸ” Scanning commit messages..."

        # Check for breaking changes (major)
        if echo "$COMMITS" | grep -iE "(BREAKING|breaking change|major)" >/dev/null; then
          BUMP_TYPE="major"
          echo "ðŸš¨ Found breaking changes â†’ major bump"
        # Check for features (minor)  
        elif echo "$COMMITS" | grep -iE "(feat|feature|minor|add)" >/dev/null; then
          BUMP_TYPE="minor"
          echo "âœ¨ Found new features â†’ minor bump"
        # Default to patch for fixes, chores, etc.
        else
          echo "ðŸ”§ Found fixes/improvements â†’ patch bump"
        fi

        # Generate changelog
        CHANGELOG=$(echo "$COMMITS" | sed 's/^[a-f0-9]* /- /' | head -20)

        echo "ðŸ“‹ Changelog preview:"
        echo "$CHANGELOG" | head -5
        if [[ $COMMIT_COUNT -gt 5 ]]; then
          echo "... and $((COMMIT_COUNT - 5)) more commits"
        fi

        # Set outputs
        echo "bump-type=$BUMP_TYPE" >> $GITHUB_OUTPUT
        echo "commit-count=$COMMIT_COUNT" >> $GITHUB_OUTPUT

        # Use heredoc for multiline changelog
        cat >> $GITHUB_OUTPUT << 'EOF'
        changelog<<CHANGELOG_EOF
        ${{ env.CHANGELOG_CONTENT }}
        CHANGELOG_EOF
        EOF

        # Store changelog in environment for the heredoc
        {
          echo "CHANGELOG_CONTENT<<CHANGELOG_HEREDOC_EOF"
          echo "$CHANGELOG"
          echo "CHANGELOG_HEREDOC_EOF"
        } >> $GITHUB_ENV
