import {
  recordLocalTimelineStep,
  recordTimelineStep,
  retryTimelineStep,
} from './activity.js';
import { timelineKitchenSink } from './workflow.js';
import type { RuntimeJsonDocument } from '../../../browser/types.js';
import type { CatalogExampleDefinition } from '../../registry.js';

const input: RuntimeJsonDocument = {
  defaultValue: [2, 3],
  schema: {
    type: 'array',
    prefixItems: [
      { title: 'Total runs', type: 'integer', minimum: 1, maximum: 4 },
      {
        title: 'Final run hold (seconds)',
        type: 'integer',
        minimum: 0,
        maximum: 120,
      },
    ],
    items: false,
    minItems: 2,
    maxItems: 2,
  },
};

const startOptions: RuntimeJsonDocument = {
  defaultValue: {},
  schema: {
    type: 'object',
    properties: { workflowId: { type: 'string', minLength: 1 } },
  },
};

export const catalogExample: CatalogExampleDefinition = {
  id: 'timeline-kitchen-sink',
  title: 'Timeline kitchen sink',
  description:
    'Creates a bounded run chain with nested children, activities, retries, signals, timers, markers, and an expected child failure.',
  capabilityTags: [
    'event-history',
    'child-workflows',
    'continue-as-new',
    'activities',
    'retries',
    'signals',
    'timers',
    'updates',
  ],
  expectedEvidence: [
    'Each run starts a child workflow that starts a nested grandchild, and parent and child exchange signals.',
    'An activity fails its first attempt and succeeds on retry; a local activity records a marker.',
    'The first run catches an expected child-workflow failure and continues as new; the final run completes.',
    'Timers start and fire in the root and nested grandchild histories; each root run also cancels a pending timer.',
  ],
  setupMarkdown:
    'The showcase runs on its own and finishes by default. Its signal events are generated by the workflows. Update history events require an external client request: while the final run is waiting, invoke the `timelineKitchenSinkUpdate` update with a string argument. Increase **Final run hold (seconds)** if you want time to send an update. Queries do not create history events, and this example does not attempt to generate every server-internal event type.',
  input,
  startOptions,
  execution: {
    kind: 'workflow',
    workflowType: 'timelineKitchenSink',
    workflow: timelineKitchenSink,
    activities: {
      recordTimelineStep,
      retryTimelineStep,
      recordLocalTimelineStep,
    },
  },
};
