export const EVENT_COLORS: Record<string, number> = {
  EVENT_TYPE_WORKFLOW_EXECUTION_STARTED: 0x10b981,
  EVENT_TYPE_WORKFLOW_EXECUTION_COMPLETED: 0x34d399,
  EVENT_TYPE_WORKFLOW_EXECUTION_FAILED: 0xef4444,
  EVENT_TYPE_WORKFLOW_EXECUTION_CANCELED: 0xfbbf24,
  EVENT_TYPE_WORKFLOW_EXECUTION_TIMED_OUT: 0xf97316,
  EVENT_TYPE_WORKFLOW_EXECUTION_SIGNALED: 0x06b6d4,
  EVENT_TYPE_WORKFLOW_TASK_SCHEDULED: 0x475569,
  EVENT_TYPE_WORKFLOW_TASK_STARTED: 0x64748b,
  EVENT_TYPE_WORKFLOW_TASK_COMPLETED: 0x94a3b8,
  EVENT_TYPE_WORKFLOW_TASK_FAILED: 0xef4444,
  EVENT_TYPE_WORKFLOW_TASK_TIMED_OUT: 0xf97316,
  EVENT_TYPE_ACTIVITY_TASK_SCHEDULED: 0x1d4ed8,
  EVENT_TYPE_ACTIVITY_TASK_STARTED: 0x3b82f6,
  EVENT_TYPE_ACTIVITY_TASK_COMPLETED: 0x60a5fa,
  EVENT_TYPE_ACTIVITY_TASK_FAILED: 0xef4444,
  EVENT_TYPE_ACTIVITY_TASK_TIMED_OUT: 0xf97316,
  EVENT_TYPE_ACTIVITY_TASK_CANCEL_REQUESTED: 0xfbbf24,
  EVENT_TYPE_ACTIVITY_TASK_CANCELED: 0xfbbf24,
  EVENT_TYPE_TIMER_STARTED: 0xd97706,
  EVENT_TYPE_TIMER_FIRED: 0xf59e0b,
  EVENT_TYPE_TIMER_CANCELED: 0xfbbf24,
  EVENT_TYPE_MARKER_RECORDED: 0xa855f7,
  EVENT_TYPE_START_CHILD_WORKFLOW_EXECUTION_INITIATED: 0xea580c,
  EVENT_TYPE_CHILD_WORKFLOW_EXECUTION_STARTED: 0xf97316,
  EVENT_TYPE_CHILD_WORKFLOW_EXECUTION_COMPLETED: 0xfb923c,
  EVENT_TYPE_CHILD_WORKFLOW_EXECUTION_FAILED: 0xef4444,
  EVENT_TYPE_CHILD_WORKFLOW_EXECUTION_CANCELED: 0xfbbf24,
  GROUP_ACTIVITY: 0x3b82f6,
  GROUP_CHILD_WORKFLOW: 0xf97316,
  GROUP_TIMER: 0xf59e0b,
  GROUP_WORKFLOW_TASK: 0x64748b,
  default: 0x6b7280,
};

export const STATUS_ALPHA: Record<string, number> = {
  scheduled: 0.5,
  started: 0.75,
  completed: 1.0,
  failed: 1.0,
  canceled: 0.55,
  fired: 1.0,
  signaled: 1.0,
};

export function colorToCss(n: number): string {
  return '#' + n.toString(16).padStart(6, '0');
}
