import { describe, expect, it } from 'vitest';

import { getSDKOrigin } from './get-sdk-origin';
import GoStacktraceQueryJson from '../../../fixtures/stacktrace-query.go-sdk.json';
import JavaStacktraceQueryJson from '../../../fixtures/stacktrace-query.java-sdk.json';
import typeScriptStacktraceQueryJson from '../../../fixtures/stacktrace-query.ts-sdk.json';

describe('getSDKOrigin', () => {
  it('should return "typescript" for a stacktrace generated by TypeScipt SDK', () => {
    const stackTraceText: string =
      typeScriptStacktraceQueryJson.queryResult.payloads[0].data;
    const result: string = getSDKOrigin(stackTraceText);
    expect(result).toEqual('typescript');
  });
  it('should return "go" for a stacktrace generated by GO SDK', () => {
    const stackTraceText: string =
      GoStacktraceQueryJson.queryResult.payloads[0].data;
    const result: string = getSDKOrigin(stackTraceText);
    expect(result).toEqual('go');
  });
  it('should return "java" for a stacktrace generated by Java SDK', () => {
    const stackTraceText: string =
      JavaStacktraceQueryJson.queryResult.payloads[0].data;
    const result: string = getSDKOrigin(stackTraceText);
    expect(result).toEqual('java');
  });
  it('should return null if origin SDK can not be determined', () => {
    const stackTraceText =
      'ImNvcm91dGluZSByb290IFtibG9ja2VkIG9uIGNoYW4tMS5SZWNlaXZlXTpcbmdvLnRlbXBvcmFsLmlvL3Nkay9pbnRlcm5hbC4oKmRlY29kZUZ1dHVyZUltcGwpLkdldCgweGMwMDAxMjc0YjgsIHsweGUwZmNmMCwgMHhjMDAwMmViNDEwfSwgezB4MD8sIDB4MH0pXG5cdC9ob21lL3VzZXIwL2dvL3BrZy9tb2QvZ28udGVtcG9yYWwuaW8vc2RrQHYxLjE0LjAvaW50ZXJuYWwvaW50ZXJuYWxfd29ya2Zsb3cuZ286MTMzNCArMHg0Y1xuZ2l0aHViLmNvbS90ZW1wb3JhbGlvL3NhbXBsZXMtZ28vdGVtcG9yYWwtZml4dHVyZXMvcmFpbmJvdy1zdGF0dXNlcy5SYWluYm93U3RhdHVzZXNXb3JrZmxvdyh7MHhlMGZjZjAsIDB4YzAwMDJlYjMyMH0sIDB4MSlcblx0L2hvbWUvdXNlcjAvc2FtcGxlcy1nby90ZW1wb3JhbC1maXh0dXJlcy9yYWluYm93LXN0YXR1c2VzL3dvcmtmbG93LmdvOjMwICsweDJkMFxucmVmbGVjdC5WYWx1ZS5jYWxsKHsweGJmOWYyMD8sIDB4ZDQ5ZWY4PywgMHg3ZmI1NjlmMGU1Yjg/fSwgezB4Y2U3NzgwLCAweDR9LCB7MHhjMDAwMmViMzUwLCAweDIsIDB4MjAzMDAwP30pXG5cdC91c3IvbGliL2dvL3NyYy9yZWZsZWN0L3ZhbHVlLmdvOjU1NiArMHg4NDVcbnJlZmxlY3QuVmFsdWUuQ2FsbCh7MHhiZjlmMjA/LCAweGQ0OWVmOD8sIDB4NDA0YzRjP30sIHsweGMwMDAyZWIzNTAsIDB4MiwgMHgyfSlcblx0L3Vzci9saWIvZ28vc3JjL3JlZmxlY3QvdmFsdWUuZ286MzM5ICsweGJmXG5nby50ZW1wb3JhbC5pby9zZGsvaW50ZXJuYWwuZXhlY3V0ZUZ1bmN0aW9uKHsweGJmOWYyMCwgMHhkNDllZjh9LCB7MHhjMDAwMTczMWEwLCAweDIsIDB4YzAwMDEwMDAwMD99KVxuXHQvaG9tZS91c2VyMC9nby9wa2cvbW9kL2dvLnRlbXBvcmFsLmlvL3Nka0B2MS4xNC4wL2ludGVybmFsL2ludGVybmFsX3dvcmtlci5nbzoxNTUzICsweDEzNlxuZ28udGVtcG9yYWwuaW8vc2RrL2ludGVybmFsLigqd29ya2Zsb3dFbnZpcm9ubWVudEludGVyY2VwdG9yKS5FeGVjdXRlV29ya2Zsb3coMHhjMDAwMmY2MjMwLCB7MHhlMGZiYTA/LCAweGMwMDAxMzFkYTB9LCAweGMwMDAxMjc0YTApXG5cdC9ob21lL3VzZXIwL2dvL3BrZy9tb2QvZ28udGVtcG9yYWwuaW8vc2RrQHYxLjE0LjAvaW50ZXJuYWwvd29ya2Zsb3cuZ286NDE5ICsweDE2NlxuZ28udGVtcG9yYWwuaW8vc2RrL2ludGVybmFsLigqd29ya2Zsb3dFeGVjdXRvcikuRXhlY3V0ZSgweGMwMDAxNmJjODAsIHsweGUwZmJhMCwgMHhjMDAwMTMxZGEwfSwgMHgyNT8pXG5cdC9ob21lL3VzZXIwL2dvL3BrZy9tb2QvZ28udGVtcG9yYWwuaW8vc2RrQHYxLjE0LjAvaW50ZXJuYWwvaW50ZXJuYWxfd29ya2VyLmdvOjc1MyArMHgyOTJcbmdvLnRlbXBvcmFsLmlvL3Nkay9pbnRlcm5hbC4oKnN5bmNXb3JrZmxvd0RlZmluaXRpb24pLkV4ZWN1dGUuZnVuYzEoezB4ZTBmY2YwLCAweGMwMDAyZWIxNzB9KVxuXHQvaG9tZS91c2VyMC9nby9wa2cvbW9kL2dvLnRlbXBvcmFsLmlvL3Nka0B2MS4xNC4wL2ludGVybmFsL2ludGVybmFsX3dvcmtmbG93LmdvOjUwMCArMHhjZCI=';
    const result: string = getSDKOrigin(stackTraceText);
    expect(result).toEqual(null);
  });
});
