version: '3.8'

services:
  temporal-ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8088:8088'
    environment:
      - TEMPORAL_ADDRESS=${TEMPORAL_ADDRESS:-temporal:7233}
      - TEMPORAL_UI_PORT=8088
      - TEMPORAL_UI_AUTH_ENABLED=true
      - TEMPORAL_UI_AUTH_PROVIDER_URL=${KEYCLOAK_URL:-http://keycloak:8080/realms/temporal-ui}
      - TEMPORAL_UI_AUTH_CLIENT_ID=${KEYCLOAK_CLIENT_ID:-temporal-ui}
      - TEMPORAL_UI_AUTH_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
      - TEMPORAL_UI_AUTH_CALLBACK_URL=${CALLBACK_URL:-http://localhost:8088/auth/sso/callback}
      - TEMPORAL_UI_AUTH_JWT_SECRET=${JWT_SECRET}
    networks:
      - temporal-network
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:8088/health',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.0
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN:-admin}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}
      - KC_DB=${KEYCLOAK_DB:-dev-file}
      - KC_HTTP_PORT=8080
      - KC_HOSTNAME=${KEYCLOAK_HOSTNAME:-localhost}
      - KC_HOSTNAME_PORT=8080
      - KC_HOSTNAME_STRICT_HTTPS=false
    ports:
      - '8080:8080'
    command: ['start-dev']
    networks:
      - temporal-network
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/health/ready']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  temporal-network:
    driver: bridge
