// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: temporal/api/operatorservice/v1/service.proto

package operatorservice

import (
	context "context"
	fmt "fmt"
	_ "github.com/gogo/googleapis/google/api"
	proto "github.com/gogo/protobuf/proto"
	v1 "go.temporal.io/api/operatorservice/v1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func init() {
	proto.RegisterFile("temporal/api/operatorservice/v1/service.proto", fileDescriptor_a603f8bc80c66d47)
}

var fileDescriptor_a603f8bc80c66d47 = []byte{
	// 316 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0x31, 0x4b, 0x03, 0x31,
	0x1c, 0xc5, 0x2f, 0x0e, 0x0e, 0x5d, 0x84, 0xc3, 0xa9, 0xc8, 0x5f, 0x70, 0x6f, 0x62, 0x2b, 0x88,
	0xa0, 0x0e, 0x3a, 0x0b, 0x82, 0xdd, 0xba, 0x48, 0x7a, 0xfe, 0xb9, 0x06, 0xda, 0xfc, 0x63, 0x92,
	0xbb, 0x45, 0x04, 0xf1, 0x13, 0x14, 0xfc, 0x12, 0x7e, 0x14, 0x17, 0xa1, 0xe0, 0xd2, 0xd1, 0x4b,
	0x1d, 0x1c, 0xfb, 0x11, 0xa4, 0x77, 0xd7, 0x0e, 0x45, 0x29, 0xb8, 0x3d, 0x92, 0xf7, 0x7e, 0xbc,
	0x97, 0x34, 0x5a, 0x1e, 0x47, 0x86, 0xac, 0x1c, 0x0a, 0x69, 0x94, 0x20, 0x83, 0x56, 0x7a, 0xb2,
	0x0e, 0x6d, 0xae, 0x12, 0x14, 0x79, 0x5b, 0xd4, 0x92, 0x1b, 0x4b, 0x9e, 0xe2, 0xfd, 0xa5, 0x9d,
	0x4b, 0xa3, 0xf8, 0x9a, 0x9d, 0xe7, 0xed, 0xe6, 0xf1, 0x26, 0x9e, 0xc5, 0xfb, 0x0c, 0x9d, 0xbf,
	0xb5, 0xe8, 0x0c, 0x69, 0x57, 0x83, 0x9b, 0x7b, 0x29, 0x51, 0x3a, 0xc4, 0x32, 0x25, 0xb5, 0x26,
	0x2f, 0xbd, 0x22, 0xed, 0xaa, 0xdb, 0x4e, 0xc1, 0x1a, 0x3b, 0xd7, 0x35, 0xab, 0x5b, 0xb1, 0xe2,
	0x77, 0xd6, 0xd8, 0xbd, 0x52, 0xce, 0x77, 0x51, 0xda, 0x64, 0x70, 0xe1, 0xbd, 0x55, 0xfd, 0xcc,
	0xa3, 0x8b, 0xcf, 0xf8, 0x86, 0x92, 0xfc, 0xb7, 0xd8, 0x4d, 0xd5, 0xab, 0x79, 0xfe, 0xcf, 0x74,
	0xb5, 0xe6, 0xe0, 0xe4, 0xf9, 0xe3, 0xeb, 0x65, 0xab, 0x13, 0x1f, 0x96, 0x4b, 0xf2, 0xb6, 0xd0,
	0x72, 0x84, 0xce, 0xc8, 0x04, 0x9d, 0x78, 0x58, 0xe9, 0x47, 0xe1, 0x4a, 0x40, 0x4b, 0xae, 0x08,
	0x97, 0x63, 0x36, 0x29, 0x20, 0x9a, 0x16, 0x10, 0xcd, 0x0b, 0x60, 0x4f, 0x01, 0xd8, 0x6b, 0x00,
	0xf6, 0x16, 0x80, 0x4d, 0x02, 0xb0, 0xcf, 0x00, 0xec, 0x3b, 0x40, 0x34, 0x0f, 0xc0, 0xc6, 0x33,
	0x88, 0x26, 0x33, 0x88, 0xa6, 0x33, 0x88, 0x7a, 0xbd, 0x54, 0xf9, 0x41, 0xd6, 0xe7, 0x09, 0x8d,
	0xc4, 0xb2, 0xb9, 0x22, 0x91, 0xa9, 0xd6, 0xa2, 0x32, 0x5a, 0x91, 0x77, 0x44, 0xad, 0x52, 0xd4,
	0x8b, 0x31, 0x78, 0xf7, 0xc7, 0xdf, 0x9c, 0xae, 0x1d, 0xf5, 0xb7, 0xcb, 0xd7, 0x3f, 0xfa, 0x09,
	0x00, 0x00, 0xff, 0xff, 0x01, 0x66, 0x8a, 0x95, 0x25, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OperatorServiceClient is the client API for OperatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OperatorServiceClient interface {
	// ListSearchAttributes returns comprehensive information about search attributes.
	ListSearchAttributes(ctx context.Context, in *v1.ListSearchAttributesRequest, opts ...grpc.CallOption) (*v1.ListSearchAttributesResponse, error)
}

type operatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOperatorServiceClient(cc grpc.ClientConnInterface) OperatorServiceClient {
	return &operatorServiceClient{cc}
}

func (c *operatorServiceClient) ListSearchAttributes(ctx context.Context, in *v1.ListSearchAttributesRequest, opts ...grpc.CallOption) (*v1.ListSearchAttributesResponse, error) {
	out := new(v1.ListSearchAttributesResponse)
	err := c.cc.Invoke(ctx, "/temporal.api.operatorservice.v1.OperatorService/ListSearchAttributes", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OperatorServiceServer is the server API for OperatorService service.
type OperatorServiceServer interface {
	// ListSearchAttributes returns comprehensive information about search attributes.
	ListSearchAttributes(context.Context, *v1.ListSearchAttributesRequest) (*v1.ListSearchAttributesResponse, error)
}

// UnimplementedOperatorServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOperatorServiceServer struct {
}

func (*UnimplementedOperatorServiceServer) ListSearchAttributes(ctx context.Context, req *v1.ListSearchAttributesRequest) (*v1.ListSearchAttributesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSearchAttributes not implemented")
}

func RegisterOperatorServiceServer(s *grpc.Server, srv OperatorServiceServer) {
	s.RegisterService(&_OperatorService_serviceDesc, srv)
}

func _OperatorService_ListSearchAttributes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1.ListSearchAttributesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorServiceServer).ListSearchAttributes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/temporal.api.operatorservice.v1.OperatorService/ListSearchAttributes",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorServiceServer).ListSearchAttributes(ctx, req.(*v1.ListSearchAttributesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OperatorService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "temporal.api.operatorservice.v1.OperatorService",
	HandlerType: (*OperatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListSearchAttributes",
			Handler:    _OperatorService_ListSearchAttributes_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "temporal/api/operatorservice/v1/service.proto",
}
