# Local development configuration for Temporal UI
temporalGrpcAddress: "10.177.51.206:30533"
port: 8088
enableUi: true
defaultNamespace: "default"
showTemporalSystemNamespace: false
notifyOnNewVersion: false
disableWriteActions: false

# Authentication configuration
auth:
  enabled: true
  jwtSecret: "your-jwt-secret-key-for-temporal-ui"
  providers:
    - label: "Keycloak Login"
      type: "oidc"
      providerUrl: "http://localhost:8080/realms/temporal-ui"
      issuerUrl: "" # Only needed if different from providerUrl
      clientId: "temporal-ui"
      clientSecret: "kRIJLLmrhnEmTT0f1hWsB3X8IcZGpBYW"
      scopes:
        - "openid"
        - "profile"
        - "email"
      callbackUrl: "http://localhost:8088/auth/sso/callback"
      useIdTokenAsBearer: false
      options: # Additional query parameters for auth provider
        audience: "temporal-ui"

# CORS configuration for local development
cors:
  cookieInsecure: true
  allowOrigins:
    - "http://localhost:8080"
    - "http://localhost:3000"
    - "http://127.0.0.1:8080"
    - "http://127.0.0.1:3000"
  unsafeAllowAllOrigins: true

# Optional: Codec configuration for data encoding/decoding
codec:
  endpoint: ""
  passAccessToken: false
  includeCredentials: false
  defaultErrorMessage: "Failed to decode data"
  defaultErrorLink: "https://docs.temporal.io/data-converters"

# Optional: Forward headers from UI to Temporal server
forwardHeaders:
  - "X-Forwarded-For"
  - "X-Real-IP"
