# Production configuration for external Temporal server with authentication
temporalGrpcAddress: "your-temporal-server:7233"
port: 8080
enableUi: true
defaultNamespace: "default"
showTemporalSystemNamespace: false
notifyOnNewVersion: true
disableWriteActions: false

# Authentication configuration
auth:
  enabled: true
  providers:
    - label: "SSO Login"
      type: "oidc"
      providerUrl: "https://your-auth-provider.com"
      issuerUrl: "" # Only needed if different from providerUrl
      clientId: "your-client-id"
      clientSecret: "your-client-secret"
      scopes:
        - "openid"
        - "profile"
        - "email"
      callbackUrl: "https://your-ui-domain:8080/auth/sso/callback"
      useIdTokenAsBearer: false
      options: # Additional query parameters for auth provider
        audience: "your-audience"
        # Add any other options your auth provider needs

# TLS configuration (if your Temporal server uses TLS)
tls:
  caFile: "/path/to/ca.cert"
  certFile: "/path/to/cert.pem"
  keyFile: "/path/to/key.pem"
  enableHostVerification: true
  serverName: "your-temporal-server"

# CORS configuration
cors:
  cookieInsecure: false
  allowOrigins:
    - "https://your-ui-domain:8080"
    - "https://your-allowed-origin.com"
  unsafeAllowAllOrigins: false

# Optional: Codec configuration for data encoding/decoding
codec:
  endpoint: "http://your-codec-server:8080"
  passAccessToken: true
  includeCredentials: false
  defaultErrorMessage: "Failed to decode data"
  defaultErrorLink: "https://docs.temporal.io/data-converters"

# Optional: Forward headers from UI to Temporal server
forwardHeaders:
  - "X-Forwarded-For"
  - "X-Real-IP"
