import { describe, expect, it } from 'vitest';

import { isFromJavaSDK } from './is-from-java-sdk';
import GoStacktraceQueryJson from '../../../fixtures/stacktrace-query.go-sdk.json';
import UnixJavaStacktraceQueryJson from '../../../fixtures/stacktrace-query.java-sdk.json';
import WindowsJavaStacktraceQueryJson from '../../../fixtures/stacktrace-query.java-sdk.windows.json';
import typeScriptStacktraceQueryJson from '../../../fixtures/stacktrace-query.ts-sdk.json';
import { stringifyWithBigInt } from '../parse-with-big-int';

describe('isFromJavaSDK', () => {
  it('should return false for a stacktrace generated by TypeScipt SDK', () => {
    const stackTraceText: string = stringifyWithBigInt(
      typeScriptStacktraceQueryJson.queryResult.payloads[0].data,
    );
    const result: boolean = isFromJavaSDK(stackTraceText);
    expect(result).toBe(false);
  });
  it('should return false for a stacktrace generated by GO SDK', () => {
    const stackTraceText: string = stringifyWithBigInt(
      GoStacktraceQueryJson.queryResult.payloads[0].data,
    );
    const result: boolean = isFromJavaSDK(stackTraceText);
    expect(result).toBe(false);
  });
  it('should return true for a stacktrace generated by Java SDK on a Unix system', () => {
    const stackTraceText: string = stringifyWithBigInt(
      UnixJavaStacktraceQueryJson.queryResult.payloads[0].data,
    );
    const result: boolean = isFromJavaSDK(stackTraceText);
    expect(result).toBe(true);
  });
  it('should return true for a stacktrace generated by Java SDK on a Windows system', () => {
    const stackTraceText: string = stringifyWithBigInt(
      WindowsJavaStacktraceQueryJson.queryResult.payloads[0].data,
    );
    const result: boolean = isFromJavaSDK(stackTraceText);
    expect(result).toBe(true);
  });
});
