import type { Component } from 'svelte';

export type RegistryEntry = {
  load: () => Promise<unknown>;
  defaultProps: Record<string, unknown>;
  children: string;
  filePath: string;
  category: string;
  requiresContext: boolean;
  variants?: Record<string, string[]>;
};

export const componentRegistry: Record<string, RegistryEntry> = {
  accordion: {
    load: () => import('$lib/holocene/accordion/accordion.svelte'),
    defaultProps: { title: 'Example Accordion' },
    children: 'Accordion content goes here.',
    filePath: 'accordion/accordion.svelte',
    category: 'Layout',
    requiresContext: false,
  },
  alert: {
    load: () => import('$lib/holocene/alert.svelte'),
    defaultProps: { intent: 'info', title: 'Alert Title' },
    children: 'This is an alert message.',
    filePath: 'alert.svelte',
    category: 'Feedback',
    requiresContext: false,
  },
  badge: {
    load: () => import('$lib/holocene/badge.svelte'),
    defaultProps: {},
    children: 'Badge',
    filePath: 'badge.svelte',
    category: 'Data Display',
    requiresContext: false,
    variants: {
      type: [
        'default',
        'primary',
        'secondary',
        'warning',
        'success',
        'danger',
        'count',
        'subtle',
      ],
    },
  },
  button: {
    load: () => import('$lib/holocene/button.svelte'),
    defaultProps: { variant: 'primary' },
    children: 'Click me',
    filePath: 'button.svelte',
    category: 'Buttons',
    requiresContext: false,
    variants: {
      variant: ['primary', 'secondary', 'destructive', 'ghost', 'table-header'],
      size: ['xs', 'sm', 'md'],
    },
  },
  calendar: {
    load: () => import('$lib/holocene/calendar.svelte'),
    defaultProps: { date: undefined, month: undefined, year: undefined },
    children: '',
    filePath: 'calendar.svelte',
    category: 'Layout',
    requiresContext: false,
  },
  card: {
    load: () => import('$lib/holocene/card.svelte'),
    defaultProps: {},
    children: 'Card content goes here.',
    filePath: 'card.svelte',
    category: 'Layout',
    requiresContext: false,
  },
  checkbox: {
    load: () => import('$lib/holocene/checkbox.svelte'),
    defaultProps: { id: 'demo', label: 'Example Label', checked: false },
    children: '',
    filePath: 'checkbox.svelte',
    category: 'Inputs',
    requiresContext: false,
  },
  chip: {
    load: () => import('$lib/holocene/chip.svelte'),
    defaultProps: { intent: 'default' },
    children: 'Chip label',
    filePath: 'chip.svelte',
    category: 'Data Display',
    requiresContext: false,
  },
  'code-block': {
    load: () => import('$lib/holocene/code-block.svelte'),
    defaultProps: { content: '{ "example": true }' },
    children: '',
    filePath: 'code-block.svelte',
    category: 'Data Display',
    requiresContext: false,
  },
  'date-picker': {
    load: () => import('$lib/holocene/date-picker.svelte'),
    defaultProps: {},
    children: '',
    filePath: 'date-picker.svelte',
    category: 'Inputs',
    requiresContext: false,
  },
  'day-of-month-picker': {
    load: () => import('$lib/holocene/day-of-month-picker.svelte'),
    defaultProps: { daysOfMonth: [] },
    children: '',
    filePath: 'day-of-month-picker.svelte',
    category: 'Inputs',
    requiresContext: false,
  },
  'day-of-week-picker': {
    load: () => import('$lib/holocene/day-of-week-picker.svelte'),
    defaultProps: { daysOfWeek: [] },
    children: '',
    filePath: 'day-of-week-picker.svelte',
    category: 'Inputs',
    requiresContext: false,
  },
  drawer: {
    load: () => import('$lib/holocene/drawer.svelte'),
    defaultProps: { flyin: false, flyout: false, onClose: () => {} },
    children: '',
    filePath: 'drawer.svelte',
    category: 'Overlays',
    requiresContext: false,
  },
  'empty-state': {
    load: () => import('$lib/holocene/empty-state.svelte'),
    defaultProps: { title: 'Nothing to show' },
    children: '',
    filePath: 'empty-state.svelte',
    category: 'Feedback',
    requiresContext: false,
  },
  'error-boundary': {
    load: () => import('$lib/holocene/error-boundary.svelte'),
    defaultProps: {},
    children: '',
    filePath: 'error-boundary.svelte',
    category: 'Feedback',
    requiresContext: false,
  },
  error: {
    load: () => import('$lib/holocene/error.svelte'),
    defaultProps: {},
    children: '',
    filePath: 'error.svelte',
    category: 'Feedback',
    requiresContext: false,
  },
  'feature-tag': {
    load: () => import('$lib/holocene/feature-tag.svelte'),
    defaultProps: { feature: 'beta' },
    children: '',
    filePath: 'feature-tag.svelte',
    category: 'Data Display',
    requiresContext: false,
  },
  'filter-or-copy-buttons': {
    load: () => import('$lib/holocene/filter-or-copy-buttons.svelte'),
    defaultProps: { content: 'example' },
    children: '',
    filePath: 'filter-or-copy-buttons.svelte',
    category: 'Data Display',
    requiresContext: false,
  },
  'icon-button': {
    load: () => import('$lib/holocene/icon-button.svelte'),
    defaultProps: {},
    children: '',
    filePath: 'icon-button.svelte',
    category: 'Buttons',
    requiresContext: false,
    variants: {
      variant: ['primary', 'secondary', 'ghost'],
    },
  },
  'chip-input': {
    load: () => import('$lib/holocene/input/chip-input.svelte'),
    defaultProps: { id: 'demo', chips: [] },
    children: '',
    filePath: 'input/chip-input.svelte',
    category: 'Inputs',
    requiresContext: false,
  },
  input: {
    load: () => import('$lib/holocene/input/input.svelte'),
    defaultProps: { id: 'demo', value: 'example', label: 'Example Label' },
    children: '',
    filePath: 'input/input.svelte',
    category: 'Inputs',
    requiresContext: false,
  },
  'number-input': {
    load: () => import('$lib/holocene/input/number-input.svelte'),
    defaultProps: { id: 'demo', value: '0', label: 'Example Label' },
    children: '',
    filePath: 'input/number-input.svelte',
    category: 'Inputs',
    requiresContext: false,
  },
  'range-input': {
    load: () => import('$lib/holocene/input/range-input.svelte'),
    defaultProps: {
      id: 'demo',
      label: 'Example Label',
      min: 0,
      max: 100,
      value: 50,
    },
    children: '',
    filePath: 'input/range-input.svelte',
    category: 'Inputs',
    requiresContext: false,
  },
  'arrow-down': {
    load: () => import('$lib/holocene/keyboard-shortcut/arrow-down.svelte'),
    defaultProps: {},
    children: '',
    filePath: 'keyboard-shortcut/arrow-down.svelte',
    category: 'Layout',
    requiresContext: false,
  },
  'arrow-left': {
    load: () => import('$lib/holocene/keyboard-shortcut/arrow-left.svelte'),
    defaultProps: {},
    children: '',
    filePath: 'keyboard-shortcut/arrow-left.svelte',
    category: 'Layout',
    requiresContext: false,
  },
  'arrow-right': {
    load: () => import('$lib/holocene/keyboard-shortcut/arrow-right.svelte'),
    defaultProps: {},
    children: '',
    filePath: 'keyboard-shortcut/arrow-right.svelte',
    category: 'Layout',
    requiresContext: false,
  },
  'arrow-up': {
    load: () => import('$lib/holocene/keyboard-shortcut/arrow-up.svelte'),
    defaultProps: {},
    children: '',
    filePath: 'keyboard-shortcut/arrow-up.svelte',
    category: 'Layout',
    requiresContext: false,
  },
  shortcut: {
    load: () => import('$lib/holocene/keyboard-shortcut/shortcut.svelte'),
    defaultProps: {},
    children: '',
    filePath: 'keyboard-shortcut/shortcut.svelte',
    category: 'Layout',
    requiresContext: false,
  },
  'labs-mode-guard': {
    load: () => import('$lib/holocene/labs-mode-guard.svelte'),
    defaultProps: {},
    children: '',
    filePath: 'labs-mode-guard.svelte',
    category: 'Layout',
    requiresContext: true,
  },
  link: {
    load: () => import('$lib/holocene/link.svelte'),
    defaultProps: { href: '#' },
    children: 'Link text',
    filePath: 'link.svelte',
    category: 'Navigation',
    requiresContext: false,
  },
  loading: {
    load: () => import('$lib/holocene/loading.svelte'),
    defaultProps: {},
    children: '',
    filePath: 'loading.svelte',
    category: 'Feedback',
    requiresContext: false,
  },
  logo: {
    load: () => import('$lib/holocene/logo.svelte'),
    defaultProps: { isCloud: false },
    children: '',
    filePath: 'logo.svelte',
    category: 'Layout',
    requiresContext: false,
  },
  'main-content-container': {
    load: () => import('$lib/holocene/main-content-container.svelte'),
    defaultProps: {},
    children: '',
    filePath: 'main-content-container.svelte',
    category: 'Layout',
    requiresContext: false,
  },
  modal: {
    load: () => import('$lib/holocene/modal.svelte'),
    defaultProps: { id: 'demo' },
    children: 'Modal content',
    filePath: 'modal.svelte',
    category: 'Overlays',
    requiresContext: false,
  },
  'month-picker': {
    load: () => import('$lib/holocene/month-picker.svelte'),
    defaultProps: { months: [] },
    children: '',
    filePath: 'month-picker.svelte',
    category: 'Inputs',
    requiresContext: false,
  },
  'orderable-list-item': {
    load: () =>
      import('$lib/holocene/orderable-list/orderable-list-item.svelte'),
    defaultProps: { label: 'Example Label' },
    children: '',
    filePath: 'orderable-list/orderable-list-item.svelte',
    category: 'Data Display',
    requiresContext: false,
  },
  'orderable-list': {
    load: () => import('$lib/holocene/orderable-list/orderable-list.svelte'),
    defaultProps: {},
    children: '',
    filePath: 'orderable-list/orderable-list.svelte',
    category: 'Data Display',
    requiresContext: false,
  },
  'page-transition': {
    load: () => import('$lib/holocene/page-transition.svelte'),
    defaultProps: {},
    children: '',
    filePath: 'page-transition.svelte',
    category: 'Layout',
    requiresContext: false,
  },
  pagination: {
    load: () => import('$lib/holocene/pagination.svelte'),
    defaultProps: { items: [] },
    children: '',
    filePath: 'pagination.svelte',
    category: 'Navigation',
    requiresContext: false,
  },
  'menu-button': {
    load: () => import('$lib/holocene/menu/menu-button.svelte'),
    defaultProps: { controls: 'demo-menu' },
    children: '',
    filePath: 'menu/menu-button.svelte',
    category: 'Buttons',
    requiresContext: true,
  },
  'menu-container': {
    load: () => import('$lib/holocene/menu/menu-container.svelte'),
    defaultProps: {},
    children: '',
    filePath: 'menu/menu-container.svelte',
    category: 'Overlays',
    requiresContext: true,
  },
  'menu-divider': {
    load: () => import('$lib/holocene/menu/menu-divider.svelte'),
    defaultProps: {},
    children: '',
    filePath: 'menu/menu-divider.svelte',
    category: 'Overlays',
    requiresContext: false,
  },
  'menu-item': {
    load: () => import('$lib/holocene/menu/menu-item.svelte'),
    defaultProps: {},
    children: 'Menu Item',
    filePath: 'menu/menu-item.svelte',
    category: 'Overlays',
    requiresContext: true,
  },
  menu: {
    load: () => import('$lib/holocene/menu/menu.svelte'),
    defaultProps: { id: 'demo' },
    children: '',
    filePath: 'menu/menu.svelte',
    category: 'Overlays',
    requiresContext: true,
  },
  'progress-bar': {
    load: () => import('$lib/holocene/progress-bar.svelte'),
    defaultProps: {},
    children: '',
    filePath: 'progress-bar.svelte',
    category: 'Feedback',
    requiresContext: false,
  },
  'filter-select': {
    load: () => import('$lib/holocene/select/filter-select.svelte'),
    defaultProps: { value: 'example' },
    children: '',
    filePath: 'select/filter-select.svelte',
    category: 'Inputs',
    requiresContext: false,
  },
  'option-group': {
    load: () => import('$lib/holocene/select/option-group.svelte'),
    defaultProps: { label: 'Example Label' },
    children: '',
    filePath: 'select/option-group.svelte',
    category: 'Inputs',
    requiresContext: false,
  },
  option: {
    load: () => import('$lib/holocene/select/option.svelte'),
    defaultProps: { value: 'example' },
    children: '',
    filePath: 'select/option.svelte',
    category: 'Inputs',
    requiresContext: true,
  },
  select: {
    load: () => import('$lib/holocene/select/select.svelte'),
    defaultProps: { id: 'demo' },
    children: '',
    filePath: 'select/select.svelte',
    category: 'Inputs',
    requiresContext: false,
  },
  'simple-option': {
    load: () => import('$lib/holocene/select/simple-option.svelte'),
    defaultProps: {},
    children: '',
    filePath: 'select/simple-option.svelte',
    category: 'Inputs',
    requiresContext: false,
  },
  'simple-select': {
    load: () => import('$lib/holocene/select/simple-select.svelte'),
    defaultProps: { id: 'demo', value: 'example' },
    children: '',
    filePath: 'select/simple-select.svelte',
    category: 'Inputs',
    requiresContext: false,
  },
  index: {
    load: () => import('$lib/holocene/select/select.svelte'),
    defaultProps: {},
    children: '',
    filePath: 'select/select.svelte',
    category: 'Inputs',
    requiresContext: false,
  },
  table: {
    load: () => import('$lib/holocene/table/table.svelte'),
    defaultProps: { variant: 'simple' },
    children: '',
    filePath: 'table/table.svelte',
    category: 'Data Display',
    requiresContext: false,
  },
  'split-button': {
    load: () => import('$lib/holocene/split-button.svelte'),
    defaultProps: { id: 'demo' },
    children: 'Click me',
    filePath: 'split-button.svelte',
    category: 'Buttons',
    requiresContext: false,
    variants: {
      variant: ['primary', 'destructive'],
    },
  },
  'tab-list': {
    load: () => import('$lib/holocene/tab/tab-list.svelte'),
    defaultProps: { label: 'Example Label' },
    children: '',
    filePath: 'tab/tab-list.svelte',
    category: 'Navigation',
    requiresContext: true,
  },
  'tab-panel': {
    load: () => import('$lib/holocene/tab/tab-panel.svelte'),
    defaultProps: { id: 'demo', tabId: 'demo-tab' },
    children: '',
    filePath: 'tab/tab-panel.svelte',
    category: 'Navigation',
    requiresContext: true,
  },
  tab: {
    load: () => import('$lib/holocene/tab/tab.svelte'),
    defaultProps: { label: 'Example Label', id: 'demo' },
    children: '',
    filePath: 'tab/tab.svelte',
    category: 'Navigation',
    requiresContext: true,
  },
  tabs: {
    load: () => import('$lib/holocene/tab/tabs.svelte'),
    defaultProps: {},
    children: '',
    filePath: 'tab/tabs.svelte',
    category: 'Navigation',
    requiresContext: false,
  },
  'table-header-row': {
    load: () => import('$lib/holocene/table/table-header-row.svelte'),
    defaultProps: {},
    children: '',
    filePath: 'table/table-header-row.svelte',
    category: 'Data Display',
    requiresContext: false,
  },
  'table-row': {
    load: () => import('$lib/holocene/table/table-row.svelte'),
    defaultProps: {},
    children: '',
    filePath: 'table/table-row.svelte',
    category: 'Data Display',
    requiresContext: false,
  },
  textarea: {
    load: () => import('$lib/holocene/textarea.svelte'),
    defaultProps: { id: 'demo', value: 'example', label: 'Example Label' },
    children: '',
    filePath: 'textarea.svelte',
    category: 'Inputs',
    requiresContext: false,
  },
  'time-picker': {
    load: () => import('$lib/holocene/time-picker.svelte'),
    defaultProps: {},
    children: '',
    filePath: 'time-picker.svelte',
    category: 'Inputs',
    requiresContext: false,
  },
  toast: {
    load: () => import('$lib/holocene/toast.svelte'),
    defaultProps: { id: 'demo', variant: 'success' },
    children: 'Toast message',
    filePath: 'toast.svelte',
    category: 'Feedback',
    requiresContext: false,
    variants: {
      variant: ['primary', 'success', 'error', 'info', 'warning'],
    },
  },
  toaster: {
    load: () => import('$lib/holocene/toaster.svelte'),
    defaultProps: { pop: () => {}, toasts: [] },
    children: '',
    filePath: 'toaster.svelte',
    category: 'Feedback',
    requiresContext: true,
  },
  'toggle-button': {
    load: () => import('$lib/holocene/toggle-button/toggle-button.svelte'),
    defaultProps: { active: false },
    children: 'Click me',
    filePath: 'toggle-button/toggle-button.svelte',
    category: 'Buttons',
    requiresContext: false,
  },
  'toggle-buttons': {
    load: () => import('$lib/holocene/toggle-button/toggle-buttons.svelte'),
    defaultProps: {},
    children: '',
    filePath: 'toggle-button/toggle-buttons.svelte',
    category: 'Buttons',
    requiresContext: true,
  },
  'toggle-switch': {
    load: () => import('$lib/holocene/toggle-switch.svelte'),
    defaultProps: { id: 'demo', checked: false },
    children: '',
    filePath: 'toggle-switch.svelte',
    category: 'Inputs',
    requiresContext: false,
  },
  tooltip: {
    load: () => import('$lib/holocene/tooltip.svelte'),
    defaultProps: { text: 'Tooltip text' },
    children: 'Hover me',
    filePath: 'tooltip.svelte',
    category: 'Overlays',
    requiresContext: false,
  },
  'collapsible-divider': {
    load: () =>
      import('$lib/holocene/collapsible-divider/collapsible-divider.svelte'),
    defaultProps: {},
    children: '',
    filePath: 'collapsible-divider/collapsible-divider.svelte',
    category: 'Layout',
    requiresContext: false,
  },
  combobox: {
    load: () => import('$lib/holocene/combobox/combobox.svelte'),
    defaultProps: {},
    children: '',
    filePath: 'combobox/combobox.svelte',
    category: 'Inputs',
    requiresContext: false,
    variants: {
      variant: ['default', 'ghost'],
    },
  },
  'radio-input': {
    load: () => import('$lib/holocene/radio-input/radio-input.svelte'),
    defaultProps: { id: 'demo', value: 'option1', label: 'Example Option' },
    children: '',
    filePath: 'radio-input/radio-input.svelte',
    category: 'Inputs',
    requiresContext: false,
  },
  'pill-container': {
    load: () => import('$lib/holocene/pill-container/pill-container.svelte'),
    defaultProps: {},
    children: '',
    filePath: 'pill-container/pill-container.svelte',
    category: 'Data Display',
    requiresContext: false,
  },
  'vertical-nav': {
    load: () => import('$lib/holocene/vertical-nav/vertical-nav.svelte'),
    defaultProps: {},
    children: '',
    filePath: 'vertical-nav/vertical-nav.svelte',
    category: 'Navigation',
    requiresContext: true,
  },
  'duration-input': {
    load: () => import('$lib/holocene/duration-input/duration-input.svelte'),
    defaultProps: {},
    children: '',
    filePath: 'duration-input/duration-input.svelte',
    category: 'Inputs',
    requiresContext: false,
  },
  'markdown-editor': {
    load: () => import('$lib/holocene/markdown-editor/markdown-editor.svelte'),
    defaultProps: {},
    children: '',
    filePath: 'markdown-editor/markdown-editor.svelte',
    category: 'Inputs',
    requiresContext: false,
  },
  portal: {
    load: () => import('$lib/holocene/portal/portal.svelte'),
    defaultProps: {},
    children: '',
    filePath: 'portal/portal.svelte',
    category: 'Overlays',
    requiresContext: false,
  },
  skeleton: {
    load: () => import('$lib/holocene/skeleton/index.svelte'),
    defaultProps: {},
    children: '',
    filePath: 'skeleton/index.svelte',
    category: 'Feedback',
    requiresContext: false,
  },
  icon: {
    load: () => import('$lib/holocene/icon/svg.svelte'),
    defaultProps: {},
    children: '',
    filePath: 'icon/svg.svelte',
    category: 'Layout',
    requiresContext: false,
  },
};

export const categories = [
  ...new Set(Object.values(componentRegistry).map((e) => e.category)),
].sort();
