import { colorAlphaScales, colorScales } from './primitives';
import type { IoTheme } from './types';

export const darkTheme = {
  color: {
    background: {
      primary: colorScales.neutral[12],
    },
    content: {
      black: '#000000',
      white: '#ffffff',
      brand: colorScales.indigo[8],
      primary: colorScales.slate[1],
      secondary: colorScales.slate[6],
      tertiary: colorScales.neutral[4],
      information: colorScales.blue[7],
      success: colorScales.green[7],
      warning: colorScales.amber[7],
      danger: colorScales.red[7],
      error: colorScales.persimmon[8],
      accent: colorScales.purple[8],
      'inverse-primary': colorScales.slate[1],
      'inverse-secondary': colorScales.slate[6],
      static: {
        information: colorScales.blue[9],
        success: colorScales.green[9],
        warning: colorScales.amber[9],
        danger: colorScales.red[9],
        neutral: colorScales.neutral[7],
      },
    },
    surface: {
      primary: colorScales.neutral[11],
      secondary: colorScales.neutral[10],
      tertiary: colorScales.neutral[9],
      neutral: colorScales.neutral[11],
      brand: colorScales.indigo[12],
      information: colorScales.blue[12],
      success: colorScales.green[12],
      warning: colorScales.amber[12],
      danger: colorScales.red[12],
      error: colorScales.persimmon[12],
      accent: colorScales.purple[12],
      overlay: {
        primary: colorAlphaScales.slate[5],
        secondary: colorAlphaScales.slate[10],
        tertiary: colorAlphaScales.slate[15],
        brand: colorAlphaScales.indigo[60],
        information: colorAlphaScales.blue[20],
        success: colorAlphaScales.green[20],
        warning: colorAlphaScales.amber[15],
        danger: colorAlphaScales.red[20],
        error: colorAlphaScales.persimmon[20],
        accent: colorAlphaScales.purple[20],
        neutral: colorAlphaScales.neutral[30],
      },
    },
    border: {
      primary: colorAlphaScales.slate[30],
      secondary: colorAlphaScales.slate[50],
      tertiary: colorAlphaScales.slate[70],
      brand: colorAlphaScales.indigo[70],
      information: colorAlphaScales.blue[70],
      success: colorAlphaScales.green[70],
      warning: colorAlphaScales.amber[70],
      danger: colorAlphaScales.red[70],
      error: colorAlphaScales.persimmon[70],
      accent: colorAlphaScales.purple[80],
    },
    interactive: {
      primary: colorScales.indigo[11],
      'primary-hover': colorScales.indigo[10],
      'primary-press': colorScales.indigo[9],
      secondary: colorScales.neutral[11],
      'secondary-hover': colorAlphaScales.indigo[10],
      'secondary-press': colorAlphaScales.indigo[20],
      'tertiary-hover': colorAlphaScales.slate[15],
      'tertiary-press': colorAlphaScales.slate[10],
      danger: colorScales.red[11],
      'danger-hover': colorScales.red[10],
      'danger-press': colorScales.red[9],
    },
    action: {
      info: colorScales.blue[10],
      success: colorScales.green[10],
      warning: colorScales.tangerine[10],
      danger: colorScales.red[10],
      workflow: {
        workflow: colorScales.zaffre[9],
        activity: colorScales['dark-magenta'][9],
        signal: colorScales.persimmon[9],
        timer: colorScales.pink[9],
        nexus: colorScales['peacock-blue'][9],
        query: colorScales['slate-blue'][9],
        capacity: colorScales.olive[9],
        fairness: colorScales.tangerine[9],
      },
    },
  },
  opacity: {
    disabled: '0.32',
  },
} satisfies IoTheme;
