import { colorAlphaScales, colorScales } from './primitives';
import type { IoTheme } from './types';

export const lightTheme = {
  color: {
    background: {
      primary: '#f8f8f8',
    },
    content: {
      black: '#000000',
      white: '#ffffff',
      brand: colorScales.indigo[9],
      primary: colorScales.slate[12],
      secondary: colorScales.slate[10],
      tertiary: colorScales.slate[8],
      information: colorScales.blue[12],
      success: colorScales.green[12],
      warning: colorScales.amber[12],
      danger: colorScales.red[12],
      error: colorScales.persimmon[12],
      accent: colorScales.purple[12],
      'inverse-primary': colorScales.slate[1],
      'inverse-secondary': colorScales.slate[6],
      static: {
        information: colorScales.blue[11],
        success: colorScales.green[11],
        warning: colorScales.amber[11],
        danger: colorScales.red[11],
        neutral: colorScales.neutral[7],
      },
    },
    surface: {
      primary: colorScales.slate[1],
      secondary: colorScales.slate[2],
      tertiary: colorScales.slate[3],
      neutral: colorScales.neutral[1],
      brand: colorScales.indigo[5],
      information: colorScales.blue[4],
      success: colorScales.green[4],
      warning: colorScales.amber[2],
      danger: colorScales.red[4],
      error: colorScales.persimmon[4],
      accent: colorScales.purple[5],
      overlay: {
        primary: colorAlphaScales.neutral[5],
        secondary: colorAlphaScales.neutral[10],
        tertiary: colorAlphaScales.neutral[15],
        brand: colorAlphaScales.indigo[30],
        information: colorAlphaScales.blue[20],
        success: colorAlphaScales.green[20],
        warning: colorAlphaScales.amber[20],
        danger: colorAlphaScales.red[20],
        error: colorAlphaScales.persimmon[20],
        accent: colorAlphaScales.purple[20],
        neutral: colorAlphaScales.neutral[30],
      },
    },
    border: {
      primary: colorAlphaScales.slate[20],
      secondary: colorAlphaScales.slate[40],
      tertiary: colorAlphaScales.slate[60],
      brand: colorScales.indigo[9],
      information: colorAlphaScales.blue[60],
      success: colorAlphaScales.green[60],
      warning: colorAlphaScales.amber[60],
      danger: colorAlphaScales.red[60],
      error: colorAlphaScales.persimmon[50],
      accent: colorAlphaScales.purple[80],
    },
    interactive: {
      primary: colorScales.indigo[9],
      'primary-hover': colorScales.indigo[10],
      'primary-press': colorScales.indigo[11],
      secondary: colorScales.slate[1],
      'secondary-hover': colorAlphaScales.indigo[10],
      'secondary-press': colorAlphaScales.indigo[15],
      'tertiary-hover': colorAlphaScales.neutral[10],
      'tertiary-press': colorAlphaScales.neutral[5],
      danger: colorScales.red[9],
      'danger-hover': colorScales.red[10],
      'danger-press': colorScales.red[11],
    },
    actions: {
      info: colorScales.blue[10],
      success: colorScales.green[10],
      warning: colorScales.tangerine[10],
      danger: colorScales.red[10],
      workflow: {
        workflow: colorScales.zaffre[9],
        activity: colorScales['dark-magenta'][9],
        signal: colorScales.pink[9],
        timer: colorScales.persimmon[9],
        nexus: colorScales['peacock-blue'][9],
        query: colorScales['slate-blue'][9],
        capacity: colorScales.olive[9],
        fairness: colorScales.tangerine[9],
      },
    },
  },
  opacity: {
    disabled: '0.32',
  },
} satisfies IoTheme;
