/* eslint-disable */
import Long from 'long';
import _m0 from 'protobufjs/minimal';

export const protobufPackage = 'temporal.api.enums.v1';

export enum WorkflowTaskFailedCause {
  WORKFLOW_TASK_FAILED_CAUSE_UNSPECIFIED = 0,
  WORKFLOW_TASK_FAILED_CAUSE_UNHANDLED_COMMAND = 1,
  WORKFLOW_TASK_FAILED_CAUSE_BAD_SCHEDULE_ACTIVITY_ATTRIBUTES = 2,
  WORKFLOW_TASK_FAILED_CAUSE_BAD_REQUEST_CANCEL_ACTIVITY_ATTRIBUTES = 3,
  WORKFLOW_TASK_FAILED_CAUSE_BAD_START_TIMER_ATTRIBUTES = 4,
  WORKFLOW_TASK_FAILED_CAUSE_BAD_CANCEL_TIMER_ATTRIBUTES = 5,
  WORKFLOW_TASK_FAILED_CAUSE_BAD_RECORD_MARKER_ATTRIBUTES = 6,
  WORKFLOW_TASK_FAILED_CAUSE_BAD_COMPLETE_WORKFLOW_EXECUTION_ATTRIBUTES = 7,
  WORKFLOW_TASK_FAILED_CAUSE_BAD_FAIL_WORKFLOW_EXECUTION_ATTRIBUTES = 8,
  WORKFLOW_TASK_FAILED_CAUSE_BAD_CANCEL_WORKFLOW_EXECUTION_ATTRIBUTES = 9,
  WORKFLOW_TASK_FAILED_CAUSE_BAD_REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION_ATTRIBUTES = 10,
  WORKFLOW_TASK_FAILED_CAUSE_BAD_CONTINUE_AS_NEW_ATTRIBUTES = 11,
  WORKFLOW_TASK_FAILED_CAUSE_START_TIMER_DUPLICATE_ID = 12,
  WORKFLOW_TASK_FAILED_CAUSE_RESET_STICKY_TASK_QUEUE = 13,
  WORKFLOW_TASK_FAILED_CAUSE_WORKFLOW_WORKER_UNHANDLED_FAILURE = 14,
  WORKFLOW_TASK_FAILED_CAUSE_BAD_SIGNAL_WORKFLOW_EXECUTION_ATTRIBUTES = 15,
  WORKFLOW_TASK_FAILED_CAUSE_BAD_START_CHILD_EXECUTION_ATTRIBUTES = 16,
  WORKFLOW_TASK_FAILED_CAUSE_FORCE_CLOSE_COMMAND = 17,
  WORKFLOW_TASK_FAILED_CAUSE_FAILOVER_CLOSE_COMMAND = 18,
  WORKFLOW_TASK_FAILED_CAUSE_BAD_SIGNAL_INPUT_SIZE = 19,
  WORKFLOW_TASK_FAILED_CAUSE_RESET_WORKFLOW = 20,
  WORKFLOW_TASK_FAILED_CAUSE_BAD_BINARY = 21,
  WORKFLOW_TASK_FAILED_CAUSE_SCHEDULE_ACTIVITY_DUPLICATE_ID = 22,
  WORKFLOW_TASK_FAILED_CAUSE_BAD_SEARCH_ATTRIBUTES = 23,
  UNRECOGNIZED = -1,
}

export function workflowTaskFailedCauseFromJSON(
  object: any,
): WorkflowTaskFailedCause {
  switch (object) {
    case 0:
    case 'WORKFLOW_TASK_FAILED_CAUSE_UNSPECIFIED':
      return WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_UNSPECIFIED;
    case 1:
    case 'WORKFLOW_TASK_FAILED_CAUSE_UNHANDLED_COMMAND':
      return WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_UNHANDLED_COMMAND;
    case 2:
    case 'WORKFLOW_TASK_FAILED_CAUSE_BAD_SCHEDULE_ACTIVITY_ATTRIBUTES':
      return WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_BAD_SCHEDULE_ACTIVITY_ATTRIBUTES;
    case 3:
    case 'WORKFLOW_TASK_FAILED_CAUSE_BAD_REQUEST_CANCEL_ACTIVITY_ATTRIBUTES':
      return WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_BAD_REQUEST_CANCEL_ACTIVITY_ATTRIBUTES;
    case 4:
    case 'WORKFLOW_TASK_FAILED_CAUSE_BAD_START_TIMER_ATTRIBUTES':
      return WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_BAD_START_TIMER_ATTRIBUTES;
    case 5:
    case 'WORKFLOW_TASK_FAILED_CAUSE_BAD_CANCEL_TIMER_ATTRIBUTES':
      return WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_BAD_CANCEL_TIMER_ATTRIBUTES;
    case 6:
    case 'WORKFLOW_TASK_FAILED_CAUSE_BAD_RECORD_MARKER_ATTRIBUTES':
      return WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_BAD_RECORD_MARKER_ATTRIBUTES;
    case 7:
    case 'WORKFLOW_TASK_FAILED_CAUSE_BAD_COMPLETE_WORKFLOW_EXECUTION_ATTRIBUTES':
      return WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_BAD_COMPLETE_WORKFLOW_EXECUTION_ATTRIBUTES;
    case 8:
    case 'WORKFLOW_TASK_FAILED_CAUSE_BAD_FAIL_WORKFLOW_EXECUTION_ATTRIBUTES':
      return WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_BAD_FAIL_WORKFLOW_EXECUTION_ATTRIBUTES;
    case 9:
    case 'WORKFLOW_TASK_FAILED_CAUSE_BAD_CANCEL_WORKFLOW_EXECUTION_ATTRIBUTES':
      return WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_BAD_CANCEL_WORKFLOW_EXECUTION_ATTRIBUTES;
    case 10:
    case 'WORKFLOW_TASK_FAILED_CAUSE_BAD_REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION_ATTRIBUTES':
      return WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_BAD_REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION_ATTRIBUTES;
    case 11:
    case 'WORKFLOW_TASK_FAILED_CAUSE_BAD_CONTINUE_AS_NEW_ATTRIBUTES':
      return WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_BAD_CONTINUE_AS_NEW_ATTRIBUTES;
    case 12:
    case 'WORKFLOW_TASK_FAILED_CAUSE_START_TIMER_DUPLICATE_ID':
      return WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_START_TIMER_DUPLICATE_ID;
    case 13:
    case 'WORKFLOW_TASK_FAILED_CAUSE_RESET_STICKY_TASK_QUEUE':
      return WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_RESET_STICKY_TASK_QUEUE;
    case 14:
    case 'WORKFLOW_TASK_FAILED_CAUSE_WORKFLOW_WORKER_UNHANDLED_FAILURE':
      return WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_WORKFLOW_WORKER_UNHANDLED_FAILURE;
    case 15:
    case 'WORKFLOW_TASK_FAILED_CAUSE_BAD_SIGNAL_WORKFLOW_EXECUTION_ATTRIBUTES':
      return WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_BAD_SIGNAL_WORKFLOW_EXECUTION_ATTRIBUTES;
    case 16:
    case 'WORKFLOW_TASK_FAILED_CAUSE_BAD_START_CHILD_EXECUTION_ATTRIBUTES':
      return WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_BAD_START_CHILD_EXECUTION_ATTRIBUTES;
    case 17:
    case 'WORKFLOW_TASK_FAILED_CAUSE_FORCE_CLOSE_COMMAND':
      return WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_FORCE_CLOSE_COMMAND;
    case 18:
    case 'WORKFLOW_TASK_FAILED_CAUSE_FAILOVER_CLOSE_COMMAND':
      return WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_FAILOVER_CLOSE_COMMAND;
    case 19:
    case 'WORKFLOW_TASK_FAILED_CAUSE_BAD_SIGNAL_INPUT_SIZE':
      return WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_BAD_SIGNAL_INPUT_SIZE;
    case 20:
    case 'WORKFLOW_TASK_FAILED_CAUSE_RESET_WORKFLOW':
      return WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_RESET_WORKFLOW;
    case 21:
    case 'WORKFLOW_TASK_FAILED_CAUSE_BAD_BINARY':
      return WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_BAD_BINARY;
    case 22:
    case 'WORKFLOW_TASK_FAILED_CAUSE_SCHEDULE_ACTIVITY_DUPLICATE_ID':
      return WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_SCHEDULE_ACTIVITY_DUPLICATE_ID;
    case 23:
    case 'WORKFLOW_TASK_FAILED_CAUSE_BAD_SEARCH_ATTRIBUTES':
      return WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_BAD_SEARCH_ATTRIBUTES;
    case -1:
    case 'UNRECOGNIZED':
    default:
      return WorkflowTaskFailedCause.UNRECOGNIZED;
  }
}

export function workflowTaskFailedCauseToJSON(
  object: WorkflowTaskFailedCause,
): string {
  switch (object) {
    case WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_UNSPECIFIED:
      return 'WORKFLOW_TASK_FAILED_CAUSE_UNSPECIFIED';
    case WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_UNHANDLED_COMMAND:
      return 'WORKFLOW_TASK_FAILED_CAUSE_UNHANDLED_COMMAND';
    case WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_BAD_SCHEDULE_ACTIVITY_ATTRIBUTES:
      return 'WORKFLOW_TASK_FAILED_CAUSE_BAD_SCHEDULE_ACTIVITY_ATTRIBUTES';
    case WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_BAD_REQUEST_CANCEL_ACTIVITY_ATTRIBUTES:
      return 'WORKFLOW_TASK_FAILED_CAUSE_BAD_REQUEST_CANCEL_ACTIVITY_ATTRIBUTES';
    case WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_BAD_START_TIMER_ATTRIBUTES:
      return 'WORKFLOW_TASK_FAILED_CAUSE_BAD_START_TIMER_ATTRIBUTES';
    case WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_BAD_CANCEL_TIMER_ATTRIBUTES:
      return 'WORKFLOW_TASK_FAILED_CAUSE_BAD_CANCEL_TIMER_ATTRIBUTES';
    case WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_BAD_RECORD_MARKER_ATTRIBUTES:
      return 'WORKFLOW_TASK_FAILED_CAUSE_BAD_RECORD_MARKER_ATTRIBUTES';
    case WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_BAD_COMPLETE_WORKFLOW_EXECUTION_ATTRIBUTES:
      return 'WORKFLOW_TASK_FAILED_CAUSE_BAD_COMPLETE_WORKFLOW_EXECUTION_ATTRIBUTES';
    case WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_BAD_FAIL_WORKFLOW_EXECUTION_ATTRIBUTES:
      return 'WORKFLOW_TASK_FAILED_CAUSE_BAD_FAIL_WORKFLOW_EXECUTION_ATTRIBUTES';
    case WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_BAD_CANCEL_WORKFLOW_EXECUTION_ATTRIBUTES:
      return 'WORKFLOW_TASK_FAILED_CAUSE_BAD_CANCEL_WORKFLOW_EXECUTION_ATTRIBUTES';
    case WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_BAD_REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION_ATTRIBUTES:
      return 'WORKFLOW_TASK_FAILED_CAUSE_BAD_REQUEST_CANCEL_EXTERNAL_WORKFLOW_EXECUTION_ATTRIBUTES';
    case WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_BAD_CONTINUE_AS_NEW_ATTRIBUTES:
      return 'WORKFLOW_TASK_FAILED_CAUSE_BAD_CONTINUE_AS_NEW_ATTRIBUTES';
    case WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_START_TIMER_DUPLICATE_ID:
      return 'WORKFLOW_TASK_FAILED_CAUSE_START_TIMER_DUPLICATE_ID';
    case WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_RESET_STICKY_TASK_QUEUE:
      return 'WORKFLOW_TASK_FAILED_CAUSE_RESET_STICKY_TASK_QUEUE';
    case WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_WORKFLOW_WORKER_UNHANDLED_FAILURE:
      return 'WORKFLOW_TASK_FAILED_CAUSE_WORKFLOW_WORKER_UNHANDLED_FAILURE';
    case WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_BAD_SIGNAL_WORKFLOW_EXECUTION_ATTRIBUTES:
      return 'WORKFLOW_TASK_FAILED_CAUSE_BAD_SIGNAL_WORKFLOW_EXECUTION_ATTRIBUTES';
    case WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_BAD_START_CHILD_EXECUTION_ATTRIBUTES:
      return 'WORKFLOW_TASK_FAILED_CAUSE_BAD_START_CHILD_EXECUTION_ATTRIBUTES';
    case WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_FORCE_CLOSE_COMMAND:
      return 'WORKFLOW_TASK_FAILED_CAUSE_FORCE_CLOSE_COMMAND';
    case WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_FAILOVER_CLOSE_COMMAND:
      return 'WORKFLOW_TASK_FAILED_CAUSE_FAILOVER_CLOSE_COMMAND';
    case WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_BAD_SIGNAL_INPUT_SIZE:
      return 'WORKFLOW_TASK_FAILED_CAUSE_BAD_SIGNAL_INPUT_SIZE';
    case WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_RESET_WORKFLOW:
      return 'WORKFLOW_TASK_FAILED_CAUSE_RESET_WORKFLOW';
    case WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_BAD_BINARY:
      return 'WORKFLOW_TASK_FAILED_CAUSE_BAD_BINARY';
    case WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_SCHEDULE_ACTIVITY_DUPLICATE_ID:
      return 'WORKFLOW_TASK_FAILED_CAUSE_SCHEDULE_ACTIVITY_DUPLICATE_ID';
    case WorkflowTaskFailedCause.WORKFLOW_TASK_FAILED_CAUSE_BAD_SEARCH_ATTRIBUTES:
      return 'WORKFLOW_TASK_FAILED_CAUSE_BAD_SEARCH_ATTRIBUTES';
    default:
      return 'UNKNOWN';
  }
}

export enum StartChildWorkflowExecutionFailedCause {
  START_CHILD_WORKFLOW_EXECUTION_FAILED_CAUSE_UNSPECIFIED = 0,
  START_CHILD_WORKFLOW_EXECUTION_FAILED_CAUSE_WORKFLOW_ALREADY_EXISTS = 1,
  UNRECOGNIZED = -1,
}

export function startChildWorkflowExecutionFailedCauseFromJSON(
  object: any,
): StartChildWorkflowExecutionFailedCause {
  switch (object) {
    case 0:
    case 'START_CHILD_WORKFLOW_EXECUTION_FAILED_CAUSE_UNSPECIFIED':
      return StartChildWorkflowExecutionFailedCause.START_CHILD_WORKFLOW_EXECUTION_FAILED_CAUSE_UNSPECIFIED;
    case 1:
    case 'START_CHILD_WORKFLOW_EXECUTION_FAILED_CAUSE_WORKFLOW_ALREADY_EXISTS':
      return StartChildWorkflowExecutionFailedCause.START_CHILD_WORKFLOW_EXECUTION_FAILED_CAUSE_WORKFLOW_ALREADY_EXISTS;
    case -1:
    case 'UNRECOGNIZED':
    default:
      return StartChildWorkflowExecutionFailedCause.UNRECOGNIZED;
  }
}

export function startChildWorkflowExecutionFailedCauseToJSON(
  object: StartChildWorkflowExecutionFailedCause,
): string {
  switch (object) {
    case StartChildWorkflowExecutionFailedCause.START_CHILD_WORKFLOW_EXECUTION_FAILED_CAUSE_UNSPECIFIED:
      return 'START_CHILD_WORKFLOW_EXECUTION_FAILED_CAUSE_UNSPECIFIED';
    case StartChildWorkflowExecutionFailedCause.START_CHILD_WORKFLOW_EXECUTION_FAILED_CAUSE_WORKFLOW_ALREADY_EXISTS:
      return 'START_CHILD_WORKFLOW_EXECUTION_FAILED_CAUSE_WORKFLOW_ALREADY_EXISTS';
    default:
      return 'UNKNOWN';
  }
}

export enum CancelExternalWorkflowExecutionFailedCause {
  CANCEL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_UNSPECIFIED = 0,
  CANCEL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_EXTERNAL_WORKFLOW_EXECUTION_NOT_FOUND = 1,
  UNRECOGNIZED = -1,
}

export function cancelExternalWorkflowExecutionFailedCauseFromJSON(
  object: any,
): CancelExternalWorkflowExecutionFailedCause {
  switch (object) {
    case 0:
    case 'CANCEL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_UNSPECIFIED':
      return CancelExternalWorkflowExecutionFailedCause.CANCEL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_UNSPECIFIED;
    case 1:
    case 'CANCEL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_EXTERNAL_WORKFLOW_EXECUTION_NOT_FOUND':
      return CancelExternalWorkflowExecutionFailedCause.CANCEL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_EXTERNAL_WORKFLOW_EXECUTION_NOT_FOUND;
    case -1:
    case 'UNRECOGNIZED':
    default:
      return CancelExternalWorkflowExecutionFailedCause.UNRECOGNIZED;
  }
}

export function cancelExternalWorkflowExecutionFailedCauseToJSON(
  object: CancelExternalWorkflowExecutionFailedCause,
): string {
  switch (object) {
    case CancelExternalWorkflowExecutionFailedCause.CANCEL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_UNSPECIFIED:
      return 'CANCEL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_UNSPECIFIED';
    case CancelExternalWorkflowExecutionFailedCause.CANCEL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_EXTERNAL_WORKFLOW_EXECUTION_NOT_FOUND:
      return 'CANCEL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_EXTERNAL_WORKFLOW_EXECUTION_NOT_FOUND';
    default:
      return 'UNKNOWN';
  }
}

export enum SignalExternalWorkflowExecutionFailedCause {
  SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_UNSPECIFIED = 0,
  SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_EXTERNAL_WORKFLOW_EXECUTION_NOT_FOUND = 1,
  UNRECOGNIZED = -1,
}

export function signalExternalWorkflowExecutionFailedCauseFromJSON(
  object: any,
): SignalExternalWorkflowExecutionFailedCause {
  switch (object) {
    case 0:
    case 'SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_UNSPECIFIED':
      return SignalExternalWorkflowExecutionFailedCause.SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_UNSPECIFIED;
    case 1:
    case 'SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_EXTERNAL_WORKFLOW_EXECUTION_NOT_FOUND':
      return SignalExternalWorkflowExecutionFailedCause.SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_EXTERNAL_WORKFLOW_EXECUTION_NOT_FOUND;
    case -1:
    case 'UNRECOGNIZED':
    default:
      return SignalExternalWorkflowExecutionFailedCause.UNRECOGNIZED;
  }
}

export function signalExternalWorkflowExecutionFailedCauseToJSON(
  object: SignalExternalWorkflowExecutionFailedCause,
): string {
  switch (object) {
    case SignalExternalWorkflowExecutionFailedCause.SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_UNSPECIFIED:
      return 'SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_UNSPECIFIED';
    case SignalExternalWorkflowExecutionFailedCause.SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_EXTERNAL_WORKFLOW_EXECUTION_NOT_FOUND:
      return 'SIGNAL_EXTERNAL_WORKFLOW_EXECUTION_FAILED_CAUSE_EXTERNAL_WORKFLOW_EXECUTION_NOT_FOUND';
    default:
      return 'UNKNOWN';
  }
}

if (_m0.util.Long !== Long) {
  _m0.util.Long = Long as any;
  _m0.configure();
}
