temporalGrpcAddress: {{ default .Env.TEMPORAL_ADDRESS "127.0.0.1:7233" }}
port: {{ default .Env.TEMPORAL_UI_PORT "8080" }}
publicPath: {{ default .Env.TEMPORAL_UI_PUBLIC_PATH "" }}
enableUi: {{ default .Env.TEMPORAL_UI_ENABLED "true" }}
cloudUi: {{ default .Env.TEMPORAL_CLOUD_UI "false" }}
enableOpenApi: {{ default .Env.TEMPORAL_OPENAPI_ENABLED "true" }}
defaultNamespace: {{ default .Env.TEMPORAL_DEFAULT_NAMESPACE "default" }}
feedbackUrl: {{ default .Env.TEMPORAL_FEEDBACK_URL "" }}
notifyOnNewVersion: {{ default .Env.TEMPORAL_NOTIFY_ON_NEW_VERSION "true" }}
refreshInterval: {{ default .Env.TEMPORAL_CONFIG_REFRESH_INTERVAL "0s" }}
showTemporalSystemNamespace:
  {{ default .Env.TEMPORAL_SHOW_TEMPORAL_SYSTEM_NAMESPACE "false" }}
disableWriteActions: {{ default .Env.TEMPORAL_DISABLE_WRITE_ACTIONS "false" }}
workflowTerminateDisabled: {{ default .Env.TEMPORAL_WORKFLOW_TERMINATE_DISABLED "false" }}
workflowCancelDisabled: {{ default .Env.TEMPORAL_WORKFLOW_CANCEL_DISABLED "false" }}
workflowSignalDisabled: {{ default .Env.TEMPORAL_WORKFLOW_SIGNAL_DISABLED "false" }}
workflowResetDisabled: {{ default .Env.TEMPORAL_WORKFLOW_RESET_DISABLED "false" }}
batchActionsDisabled: {{ default .Env.TEMPORAL_BATCH_ACTIONS_DISABLED "false" }}
cors:
  cookieInsecure: {{ default .Env.TEMPORAL_CSRF_COOKIE_INSECURE "false" }}
  allowOrigins:
    # override framework's default that allows all origins "*"
    - {{ default .Env.TEMPORAL_CORS_ORIGINS "http://localhost:8080" }}
tls:
  caFile: {{ default .Env.TEMPORAL_TLS_CA "" }}
  certFile: {{ default .Env.TEMPORAL_TLS_CERT "" }}
  keyFile: {{ default .Env.TEMPORAL_TLS_KEY "" }}
  caData: {{ default .Env.TEMPORAL_TLS_CA_DATA "" }}
  certData: {{ default .Env.TEMPORAL_TLS_CERT_DATA "" }}
  keyData: {{ default .Env.TEMPORAL_TLS_KEY_DATA "" }}
  enableHostVerification: {{ default .Env.TEMPORAL_TLS_ENABLE_HOST_VERIFICATION "false" }}
  serverName: {{ default .Env.TEMPORAL_TLS_SERVER_NAME "" }}
auth:
  enabled: {{ default .Env.TEMPORAL_AUTH_ENABLED "false" }}
  providers:
  - label: {{ default .Env.TEMPORAL_AUTH_LABEL "sso" }}
    type: {{ default .Env.TEMPORAL_AUTH_TYPE "oidc" }}
    providerUrl: {{ .Env.TEMPORAL_AUTH_PROVIDER_URL }}
    issuerUrl: {{ default .Env.TEMPORAL_AUTH_ISSUER_URL "" }}
    clientId: {{ .Env.TEMPORAL_AUTH_CLIENT_ID }}
    clientSecret: {{ .Env.TEMPORAL_AUTH_CLIENT_SECRET }}
    callbackUrl: {{ .Env.TEMPORAL_AUTH_CALLBACK_URL }}
    scopes: {{ if .Env.TEMPORAL_AUTH_SCOPES }} {{ range $seed := (split .Env.TEMPORAL_AUTH_SCOPES ",") }}
      - {{ . }} {{ end }} {{ end }}
codec:
  endpoint: {{ default .Env.TEMPORAL_CODEC_ENDPOINT "" }}
  passAccessToken: {{ default .Env.TEMPORAL_CODEC_PASS_ACCESS_TOKEN "false" }}
forwardHeaders: {{ if .Env.TEMPORAL_FORWARD_HEADERS }} {{ range $seed := (split .Env.TEMPORAL_FORWARD_HEADERS ",") }}
  - {{ . }} {{ end }} {{ end }}
