/**
 * Writes the stylesheet the Go render route embeds.
 *
 * server/server/route/ui.go serves /render in a packaged ui-server, where no
 * SvelteKit server runs. It cannot import src/lib/utilities/markdown-reset.ts
 * — server/ is a separate Go module, so //go:embed cannot reach outside it —
 * and it cannot resolve the Io theme colours, which only exist as TypeScript.
 * So the stylesheet the SvelteKit route serves is written out here and checked
 * in for the Go build to embed.
 *
 * Run with `pnpm generate:markdown-css`. generate-markdown-css.test.ts fails
 * if the checked-in file falls behind either input.
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { markdownStylesheet } from '../src/lib/utilities/markdown-stylesheet';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

export const GENERATED_PATH = join(
  root,
  'server',
  'server',
  'route',
  'markdown.gen.css',
);

const BANNER = `/*
 * Generated by scripts/generate-markdown-css.ts. Do not edit.
 *
 * Source: src/lib/utilities/markdown-reset.ts plus the Io theme colours the
 * reset refers to. Run \`pnpm generate:markdown-css\` after changing either.
 */
`;

export const buildGeneratedStylesheet = (): string =>
  `${BANNER}${markdownStylesheet}`;

const isEntrypoint = process.argv[1] === fileURLToPath(import.meta.url);

if (isEntrypoint) {
  writeFileSync(GENERATED_PATH, buildGeneratedStylesheet());
  console.log(`wrote ${GENERATED_PATH}`);
}
