/**
 * Writes the stylesheet the Go render route embeds.
 *
 * server/server/route/ui.go serves /render in a packaged ui-server, where no
 * SvelteKit server runs. It cannot read src/markdown.reset.css — server/ is a
 * separate Go module, so //go:embed cannot reach outside it — and it cannot
 * resolve the Io theme colours, which only exist as TypeScript. So the
 * stylesheet is composed here, by the same function the SvelteKit route calls,
 * and checked in for the Go build to embed.
 *
 * Run with `pnpm generate:markdown-css`. markdown-stylesheet.test.ts fails if
 * the checked-in file falls behind either input.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { composeMarkdownStylesheet } from '../src/lib/utilities/markdown-stylesheet';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

export const RESET_PATH = join(root, 'src', 'markdown.reset.css');
export const GENERATED_PATH = join(
  root,
  'server',
  'server',
  'route',
  'markdown.gen.css',
);

const BANNER = `/*
 * Generated by scripts/generate-markdown-css.ts. Do not edit.
 *
 * Source: src/markdown.reset.css plus the Io theme colours the reset refers
 * to. Run \`pnpm generate:markdown-css\` after changing either.
 */
`;

export const buildGeneratedStylesheet = (): string =>
  `${BANNER}${composeMarkdownStylesheet(readFileSync(RESET_PATH, 'utf8'))}`;

const isEntrypoint = process.argv[1] === fileURLToPath(import.meta.url);

if (isEntrypoint) {
  writeFileSync(GENERATED_PATH, buildGeneratedStylesheet());
  console.log(`wrote ${GENERATED_PATH}`);
}
