# Temporal Server Configuration with TLS
log:
  stdout: true
  level: info

persistence:
  defaultStore: default
  visibilityStore: visibility
  numHistoryShards: 4
  datastores:
    default:
      sql:
        pluginName: "postgres"
        databaseName: "temporal"
        connectAddr: "postgresql:5432"
        connectProtocol: "tcp"
        user: "temporal"
        password: "temporal"
        maxConns: 20
        maxIdleConns: 20
        maxConnLifetime: "1h"
        tls:
          enabled: false
    visibility:
      sql:
        pluginName: "postgres"
        databaseName: "temporal_visibility"
        connectAddr: "postgresql:5432"
        connectProtocol: "tcp"
        user: "temporal"
        password: "temporal"
        maxConns: 10
        maxIdleConns: 10
        maxConnLifetime: "1h"
        tls:
          enabled: false

global:
  membership:
    maxJoinDuration: 30s
    broadcastAddress: "0.0.0.0"

  # TLS Configuration for Frontend Service
  tls:
    internode:
      # TLS for inter-node communication (between Temporal services)
      server:
        requireClientAuth: true
        certFile: /etc/temporal/certs/server.crt
        keyFile: /etc/temporal/certs/server.key
        clientCaFiles:
          - /etc/temporal/certs/ca.crt
      client:
        serverName: temporal-server
        rootCaFiles:
          - /etc/temporal/certs/ca.crt

    frontend:
      # TLS for client connections
      server:
        requireClientAuth: true # Mutual TLS
        certFile: /etc/temporal/certs/server.crt
        keyFile: /etc/temporal/certs/server.key
        clientCaFiles:
          - /etc/temporal/certs/ca.crt

      # This client section is used to configure the TLS clients within
      # the Temporal Cluster (specifically the Worker role) that connect to the Frontend service
      client:
        serverName: temporal-server
        rootCaFiles:
          - /etc/temporal/certs/ca.crt

services:
  frontend:
    rpc:
      grpcPort: 7233
      membershipPort: 6933
      bindOnLocalHost: false
      # Enable TLS
      tls:
        certFile: /etc/temporal/certs/server.crt
        keyFile: /etc/temporal/certs/server.key
        clientCaFiles:
          - /etc/temporal/certs/ca.crt
        requireClientAuth: true

  matching:
    rpc:
      grpcPort: 7235
      membershipPort: 6935
      bindOnLocalHost: false
      tls:
        certFile: /etc/temporal/certs/server.crt
        keyFile: /etc/temporal/certs/server.key
        clientCaFiles:
          - /etc/temporal/certs/ca.crt
        requireClientAuth: true

  history:
    rpc:
      grpcPort: 7234
      membershipPort: 6934
      bindOnLocalHost: false
      tls:
        certFile: /etc/temporal/certs/server.crt
        keyFile: /etc/temporal/certs/server.key
        clientCaFiles:
          - /etc/temporal/certs/ca.crt
        requireClientAuth: true

  worker:
    rpc:
      grpcPort: 7239
      membershipPort: 6939
      bindOnLocalHost: false
      tls:
        certFile: /etc/temporal/certs/server.crt
        keyFile: /etc/temporal/certs/server.key
        clientCaFiles:
          - /etc/temporal/certs/ca.crt
        requireClientAuth: true

clusterMetadata:
  enableGlobalNamespace: false
  failoverVersionIncrement: 10
  masterClusterName: "active"
  currentClusterName: "active"
  clusterInformation:
    active:
      enabled: true
      initialFailoverVersion: 1
      rpcName: "frontend"
      rpcAddress: "0.0.0.0:7233"

dcRedirectionPolicy:
  policy: "noop"

archival:
  history:
    state: "disabled"
    enableRead: true
    provider:
      filestore:
        fileMode: "0666"
        dirMode: "0766"
  visibility:
    state: "disabled"
    enableRead: true
    provider:
      filestore:
        fileMode: "0666"
        dirMode: "0766"

namespaceDefaults:
  archival:
    history:
      state: "disabled"
    visibility:
      state: "disabled"

publicClient:
  hostPort: "0.0.0.0:7233"
