name: 'Chromatic'

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, 'codefreeze-*']

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Checkout and Setup Node
        uses: ./.github/actions/checkout-and-setup
      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: 'main'
          exitZeroOnChanges: true
          exitOnceUploaded: true
          onlyChanged: true
          skip: 'dependabot/**'
