name: 'Chromatic'

on:
  push:
    branches: [main]
  pull_request_target:
    branches: [main, 'codefreeze-*']

permissions:
  contents: read
  pull-requests: write
  statuses: write

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
      - name: Checkout and Setup Node
        uses: ./.github/actions/setup-node
      - name: Run Chromatic
        uses: chromaui/action@14cfaef73576e69f95f47f60058063f46ca38719 # v18.1.0
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: 'main'
          exitZeroOnChanges: true
          exitOnceUploaded: true
          onlyChanged: true
          skip: 'dependabot/**'
