name: Danger

on:
  pull_request:
    branches: [main, 'codefreeze-*']

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0

      - name: Setup Node and Dependencies
        uses: ./.github/actions/setup-node

      - name: Generate token for Danger
        id: generate_token
        uses: actions/create-github-app-token@1b10c78c7865c340bc4f6099eb2f838309f1e8c3 # v3.1.1
        with:
          client-id: ${{ secrets.TEMPORAL_CICD_APP_ID }}
          private-key: ${{ secrets.TEMPORAL_CICD_PRIVATE_KEY }}
          owner: temporalio
          repositories: ui

      - name: Run Danger
        run: pnpm exec danger ci --failOnErrors
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
