name: Danger

on:
  pull_request:
    branches: [main, 'codefreeze-*']

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  danger:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0

      - name: Setup Node and Dependencies
        uses: ./.github/actions/setup-node

      - name: Generate token for Danger
        id: generate_token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          client-id: ${{ secrets.TEMPORAL_CICD_APP_ID }}
          private-key: ${{ secrets.TEMPORAL_CICD_PRIVATE_KEY }}
          owner: temporalio
          repositories: ui

      - name: Run Danger
        run: pnpm exec danger ci --failOnErrors
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
