name: Snapshot Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  snapshot-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Install modules
        run: pnpm install
      - name: Run snapshot tests
        run: pnpm snapshot
