name: Server Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, 'codefreeze-*']

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: true
      - name: Checkout and setup Node
        uses: ./.github/actions/setup-node
      - name: Build UI
        run: pnpm build:server

      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version-file: server/go.mod
          cache-dependency-path: server/go.sum
          cache: true
          check-latest: true
      - name: build
        working-directory: server
        run: make build

      - name: test
        working-directory: server
        run: make test
