name: Trigger Downstream Updates

on:
  push:
    branches:
      - main
    # paths:
    # Only trigger when actual code changes are made
    # - 'src/**'
    # - 'package.json'
    # - 'pnpm-lock.yaml'
  workflow_dispatch:
    inputs:
      target-sha:
        description: 'Specific SHA to use (defaults to current HEAD)'
        required: false
        default: ''

jobs:
  trigger-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate token for cross-repo access
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.TEMPORAL_CICD_APP_ID }}
          private-key: ${{ secrets.TEMPORAL_CICD_PRIVATE_KEY }}
          owner: temporalio
          repositories: cloud-ui,ui,pack-dependency-actions

      - name: Prepare workflow inputs
        id: prepare
        run: |
          # Determine SHA to use
          if [ -n "${{ github.event.inputs.target-sha }}" ]; then
            SHA="${{ github.event.inputs.target-sha }}"
          else
            SHA="${{ github.sha }}"
          fi

          # Create workflow inputs JSON (compact format for GITHUB_OUTPUT)
          INPUTS=$(jq -nc \
            --arg sha "$SHA" \
            --arg mode "release" \
            '{"ui_commit_sha": $sha, "mode": $mode}')

          echo "inputs=$INPUTS" >> $GITHUB_OUTPUT
          echo "sha=$SHA" >> $GITHUB_OUTPUT
          echo "sha_short=$(echo $SHA | cut -c1-8)" >> $GITHUB_OUTPUT
          echo "Using SHA: $(echo $SHA | cut -c1-8)"

      - name: Trigger cloud-ui update
        uses: temporalio/pack-dependency-actions/dispatch-workflow@main
        with:
          token: ${{ steps.generate_token.outputs.token }}
          repository: temporalio/cloud-ui
          workflow: generate-ui-pr.yml
          ref: main
          inputs: ${{ steps.prepare.outputs.inputs }}
          add-commit-comment: true
          commit-comment-template: '🚀 Triggered `{workflow}` in {repository} on {ref} with SHA `${{ steps.prepare.outputs.sha_short }}`'
          log-title: Downstream Update Triggered
